2019-06-05 16:01:40,869 ERROR: Exception on /login [GET] [in c:\users\teperchuk-av\envs\flask_project\lib\site-packages\flask\app.py:1780]
Traceback (most recent call last):
  File "c:\users\teperchuk-av\envs\flask_project\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\teperchuk-av\envs\flask_project\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\teperchuk-av\envs\flask_project\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\teperchuk-av\envs\flask_project\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\teperchuk-av\envs\flask_project\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\teperchuk-av\envs\flask_project\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\teperchuk-av\www\microbloge_work\app\routes.py", line 49, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\users\teperchuk-av\envs\flask_project\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\teperchuk-av\envs\flask_project\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\teperchuk-av\envs\flask_project\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\teperchuk-av\envs\flask_project\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\teperchuk-av\envs\flask_project\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\teperchuk-av\envs\flask_project\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\teperchuk-av\www\microbloge_work\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\teperchuk-av\www\microbloge_work\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\teperchuk-av\www\microbloge_work\app\templates\login.html", line 33, in block "content"
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "c:\users\teperchuk-av\envs\flask_project\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\teperchuk-av\envs\flask_project\lib\site-packages\flask\app.py", line 2080, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\teperchuk-av\envs\flask_project\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\teperchuk-av\envs\flask_project\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\users\teperchuk-av\envs\flask_project\lib\site-packages\werkzeug\routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2019-06-05 16:25:25,708 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:45]
2019-06-05 16:29:59,013 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:45]
2019-06-06 09:06:17,824 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:45]
2019-06-06 09:28:55,568 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:48]
2019-06-06 09:35:27,582 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:48]
2019-06-06 09:38:12,036 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:48]
2019-06-06 09:43:56,083 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:48]
2019-06-06 09:45:38,788 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:48]
2019-06-06 09:51:48,012 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:48]
2019-06-06 09:55:11,207 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:48]
2019-06-06 10:11:13,078 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:50]
2019-06-06 10:11:45,381 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:50]
2019-06-06 11:07:53,422 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:52]
2019-06-06 11:09:34,651 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:52]
2019-06-06 11:10:08,294 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:52]
2019-06-06 11:10:35,762 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:52]
2019-06-06 16:54:15,198 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:55]
2019-06-10 15:06:00,416 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:55]
2019-06-10 15:25:34,971 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:55]
2019-06-10 15:26:08,860 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:55]
2019-06-10 16:22:07,139 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:55]
2019-06-10 16:25:25,892 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:55]
2019-06-10 16:27:30,162 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:55]
2019-06-10 16:34:30,054 INFO: Microblog startup [in C:\Users\teperchuk-av\www\microbloge_work\app\__init__.py:55]
